### ISSUE TITLE
Issue in crawling websites with the latest OpenWPM install

### ISSUE THREAD

**Issue by nayanamana** [mozilla/OpenWPM#257]
Today, I tried installing OpenWPM on Ubuntu 16.04 and when tried to run demo.py (without modifications), I am getting connection refused errors after some time. I've installed/used OpenWPM in the past successfully. Have anything changed in the OpenWPM sources in github lately that may be the cause for this issue?

2019-02-08 02:21:02,534 - MainProcess[MainThread] - BrowserManager       - ERROR   : BROWSER 2: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
2019-02-08 02:21:02,534 - MainProcess[log-interceptor-2] - selenium_firefox     - DEBUG   : BROWSER 2: driver: 1549592401338	geckodriver	INFO	Listening on 127.0.0.1:59374
2019-02-08 02:21:02,534 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 2: Attempting to kill BrowserManager with pid 1707. Display PID: None | Display Port: None | Browser PID: None
2019-02-08 02:21:02,535 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 2: Spawn attempt 3 
2019-02-08 02:21:02,547 - MainProcess[MainThread] - deploy_firefox       - DEBUG   : BROWSER 2: OpenWPM Firefox extension loaded
2019-02-08 02:21:05,654 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:10,660 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:15,665 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:20,671 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:25,676 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:30,682 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:35,687 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:40,693 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:45,698 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:50,704 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:21:55,709 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:22:00,715 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-02-08 02:22:03,753 - MainProcess[MainThread] - BrowserManager       - INFO    : BROWSER 2: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/ubuntu/install/OpenWPM/automation/BrowserManager.py", line 347, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/ubuntu/install/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/home/ubuntu/install/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 161, in deploy_firefox
    firefox_options=fo, log_path=interceptor.fifo)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: connection refused

**Comment by englehardt** [comment]
This looks like Firefox is having problems starting. Two suggestions:
* Rerun `install.sh` to make sure you have the newest version of Firefox
* If you're running on a server or other headless environment, ensure that the headless configuration option is set to true for all browsers.

**Comment by nayanamana** [comment]
I ran install.sh few times after the first install, but didn't resolve the
issue. First, I encountered the issue on a Amazon EC2 Ubuntu 16.04 machine.
Then the same issue was recreated on a physical machine running Ubuntu
16.04.

However, if I install an old version of OpenWPM on any of the machines
mentioned above,  OpenWPM works.

**Comment by nayanamana** [comment]
Actually below configuration in demo.py resolved the issue. It's just that it is not a default configuration in demo.py. Thanks for the previous hint.

 browser_params[i]['headless'] = True
