### ISSUE TITLE
ConnectionAbortedError: [Errno 53] Software caused connection abort

### ISSUE THREAD

**Issue by wagnerand** [mozilla/OpenWPM#278]
Running `demo.py` on a macOS 10.14.4 machine yields the following errors:

```
BaseAggregator       - INFO     - Received shutdown signal!
Exception in thread Thread-1-LocalListener:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/awagner/mozilla/OpenWPM/automation/SocketInterface.py", line 43, in _accept
    (client, address) = self.sock.accept()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
ConnectionAbortedError: [Errno 53] Software caused connection abort

Exception in thread Thread-1-loggingserver:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/awagner/mozilla/OpenWPM/automation/SocketInterface.py", line 43, in _accept
    (client, address) = self.sock.accept()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
ConnectionAbortedError: [Errno 53] Software caused connection abort
```

I tracked it down to the `sleep` calls in https://github.com/mozilla/OpenWPM/blob/master/automation/DataAggregator/BaseAggregator.py#L97 and https://github.com/mozilla/OpenWPM/blob/master/automation/MPLogger.py#L122. If I remove those, the errors do not occur.

**Comment by motin** [comment]
@wagnerand Could you supply steps to reproduce your environment and execute demo.py, as if you'd started on a stock macOS 10.14.4 installation? Are you following specific docs? Using venv?

**Comment by felix4webscience** [comment]
Hi  @wagnerand <https://github.com/wagnerand>  ,

you are using python3.7, right? Does the same problem occur, if you use
python2.7?

Am Di., 9. Apr. 2019 um 18:38 Uhr schrieb Andreas Wagner <
notifications@github.com>:

**Comment by englehardt** [comment]
I looked into this a bit. What's happening is something is trying to create a new connection to a socket that's already closed. If we don't sleep or drain the queue, the connection attempt is never made because the platform is able to finish shutdown before the new connection attempt occurs. I suspect, but need to verify, that the same connection attempt occurs on other platforms, but doesn't error on other platforms.

It would be nice to figure out what is trying to start a new connection on shutdown. A temporary solution is to wrap https://github.com/mozilla/OpenWPM/blob/b3ead7e38892095950806e8bcbb2e1129c27ca96/automation/SocketInterface.py#L43 in a try-except for `ConnectionAbortedError`, print a message that a connection establish request was performed on a closed socket, and return.

**Comment by motin** [comment]
After getting the latest master branch of OpenWPM to run (https://github.com/mozilla/OpenWPM/pull/283), I was able to reproduce this issue simply by running `python demo.py`

**Comment by motin** [comment]
@englehardt Like this?

```
            try:
                (client, address) = self.sock.accept()
                thread = threading.Thread(target=self._handle_conn,
                                          args=(client, address))
                thread.daemon = True
                thread.start()
            except ConnectionAbortedError:
                print("A connection establish request was performed on a closed socket")
                return
```

That workaround allows the crawl to run, and at the end of the crawl, the following is reported:

```
BaseAggregator       - INFO     - Received shutdown signal!
A connection establish request was performed on a closed socket
A connection establish request was performed on a closed socket
```

**Comment by motin** [comment]
The effect of this is that the browser windows stay open after the crawl has finished

**Comment by englehardt** [comment]
@motin yes exactly. that should work for now until we're able to chase down the cause and ensure it's nothing we care about

**Comment by englehardt** [comment]
Closing due to inactivity. Feel free to file a new issue if you're still having problems.
