### ISSUE TITLE
Parquet output fails with: Conversion failed for column visit_id with type object

### ISSUE THREAD

**Issue by wagnerand** [mozilla/OpenWPM#286]
I tried s3 storing, following the instructions on `https://github.com/mozilla/OpenWPM#parquet-on-amazon-s3-experimental` and I'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/awagner/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 40, in listener_process_runner
    listener.process_record(record)
  File "/Users/awagner/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 225, in process_record
    self._create_batch(self.browser_map[crawl_id])
  File "/Users/awagner/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 97, in _create_batch
    df, schema=PQ_SCHEMAS[table_name], preserve_index=False
  File "pyarrow/table.pxi", line 858, in pyarrow.lib.RecordBatch.from_pandas
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 468, in dataframe_to_arrays
    convert_types)]
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 467, in <listcomp>
    for c, t in zip(columns_to_convert,
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 463, in convert_column
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 457, in convert_column
    return pa.array(col, type=ty, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 169, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 78, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('an integer is required (got type str)', 'Conversion failed for column visit_id with type object')
```

Running the exact same script except using a local (sqlite) output works.

**Comment by englehardt** [comment]
@nhnt11 I observe this on the master branch when running demo.py. Parquet expects inputs to be the right type (unlike sqlite, which will cast them), so the most likely cause here is simply that we're sending the wrong type back from the extension to the data aggregator.

When we fix this, we should add unit tests to the parquet aggregator to catch these issues in the future.

**Comment by motin** [comment]
I started a branch for fixing this in https://github.com/motin/OpenWPM/tree/fix-issue-286, but simply fixing the type of visit_id is not enough. There are multiple inconsistencies between the parquet schema and what the instrumentation add-on sends.

**Comment by englehardt** [comment]
I noticed this as well. I'd like to understand where the types are getting dropped up since https://github.com/mozilla/openwpm-webext-instrumentation/blob/master/src/schema.ts does have the correct types specified.  We should only fix this in the aggregator as a last resort.

**Comment by englehardt** [comment]
I've also noticed inconsistencies for the same column across tables; e.g., for the `site_visit` table  `visit_id` is `long`, but for all other tables it's `unicode`.

**Comment by motin** [comment]
> We should only fix this in the aggregator as a last resort.
True. Only for visit_id is it correct to fix it in the aggregator, since that is where it is originally set.
