### ISSUE TITLE
Locked database

### ISSUE THREAD

**Issue by wagnerand** [mozilla/OpenWPM#307]
I often get the following error during bulk-crawling of add-ons:

```
Traceback (most recent call last):
  File "crawl-good-addons.py", line 38, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params)
  File "/Users/awagner/mozilla/coe/OpenWPM/automation/TaskManager.py", line 132, in __init__
    self.data_aggregator.save_configuration(openwpm_v, browser_v)
  File "/Users/awagner/mozilla/coe/OpenWPM/automation/DataAggregator/LocalAggregator.py", line 230, in save_configuration
    openwpm_version, browser_version)
sqlite3.OperationalError: database is locked
```

**Comment by englehardt** [comment]
Would you mind to share the script you're using to start and run the crawler? E.g., the equivalent of [demo.py](https://github.com/mozilla/OpenWPM/blob/master/demo.py)

**Comment by wagnerand** [comment]
https://gist.github.com/wagnerand/7acc9077e6bc79a76e33f2ff5bb0a1e2

**Comment by englehardt** [comment]
Closing due to inactivity. Please re-open if you're still having the issue.
