### ISSUE TITLE
Alerts causing `WebDriverException: Message: Failed to decode response from marionette`?

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#404]
Not sure what this one is about, apparently something related to reading the value of alerts (`self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]`) causing this crash?

Log output:
```
BrowserManager       - INFO     - BROWSER -1312820091: EXECUTING COMMAND: ('GET', u'http://ltn.com.tw', 10, -1446733757290209L)
BrowserManager       - INFO     - BROWSER -1312820091: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 420, in BrowserManager
    browser_params, manager_params, extension_socket)
  File "/opt/OpenWPM/automation/Commands/command_executor.py", line 15, in execute_command
    extension_socket=extension_socket)
  File "/opt/OpenWPM/automation/Commands/browser_commands.py", line 131, in get_website
    WebDriverWait(webdriver, .5).until(EC.alert_is_present())
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/expected_conditions.py", line 401, in __call__
    alert = driver.switch_to.alert
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Failed to decode response from marionette
TaskManager          - INFO     - BROWSER -1312820091: Received failure status while executing command: GET
```

**Comment by englehardt** [comment]
Related to #255. We should take note of all of these types errors in the WebExtension crawls and fix where possible. The current crash rate is quite high.

**Comment by englehardt** [comment]
This crash is quite common. I suspect it's happening almost every time there's and alert or modal dialog box on a site. We should set up a test page with a couple different styles of alerts and see if we can close them without causing this error.

**Comment by motin** [comment]
Important comments regarding this are found in https://github.com/mozilla/OpenWPM/pull/449#issuecomment-520682990 and https://github.com/mozilla/OpenWPM/pull/449#discussion_r313225389

**Comment by motin** [comment]
Possibly related: https://stackoverflow.com/questions/44215846/handling-popup-windows-in-selenium?rq=1
