### ISSUE TITLE
problem of instantizing firefox browser: XStartTimeoutError: Failed to start X on display ":1001" (xdpyinfo check failed)

### ISSUE THREAD

**Issue by gitbbb** [mozilla/OpenWPM#424]
Hi, these days I tried to deploy OpenWRT but had an issue with no obvious solution.
 
# My environment

|  1  | 2  |
|  ----  | ----  |
| OS  | Linux Mint 19.1 Cinnamon |
| Kernel  | 4.15.0-20-generic |

I sucessfully run install.sh script. The log is too long so I refer it in evernote [here](https://www.evernote.com/shard/s724/sh/90b3122a-cef9-485f-87c2-2f433a59c029/3a20720dfb55102a47ecde22dd4ec801).

For demo.py, default_browser_params.json, default_manager_params.json, I kept them with no modification.

Then, I try to run demo with command 'python demo.py' but I encounter the following error that I cannot find a way to solve it. Also, for better reading experience I put a refer link [here](https://www.evernote.com/shard/s724/sh/54603be7-6251-4de2-8a75-e6a6e878ff05/3685340af2be44b2ac1e18ff43efe678)

```
2019-07-25 13:10:31,939 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Spawn attempt 0 
2019-07-25 13:10:36,944 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:10:41,950 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:10:42,020 - MainProcess[MainThread] - BrowserManager       - INFO    : BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_firefox.py", line 105, in deploy_firefox
    display.start()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/abstractdisplay.py", line 168, in start
    raise XStartTimeoutError(msg % d)
XStartTimeoutError: Failed to start X on display ":1001" (xdpyinfo check failed).

2019-07-25 13:10:42,021 - MainProcess[MainThread] - BrowserManager       - ERROR   : BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: False  | Browser Launched: False  | Browser Ready: False 
2019-07-25 13:10:42,022 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Attempting to kill BrowserManager with pid 18867. Display PID: None | Display Port: None | Browser PID: None
2019-07-25 13:10:42,022 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Spawn attempt 1 
2019-07-25 13:10:46,955 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:10:51,961 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:10:52,173 - MainProcess[MainThread] - BrowserManager       - INFO    : BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_firefox.py", line 105, in deploy_firefox
    display.start()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/abstractdisplay.py", line 168, in start
    raise XStartTimeoutError(msg % d)
XStartTimeoutError: Failed to start X on display ":1001" (xdpyinfo check failed).

2019-07-25 13:10:52,175 - MainProcess[MainThread] - BrowserManager       - ERROR   : BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: False  | Browser Launched: False  | Browser Ready: False 
2019-07-25 13:10:52,176 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Attempting to kill BrowserManager with pid 18977. Display PID: None | Display Port: None | Browser PID: None
2019-07-25 13:10:52,176 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Spawn attempt 2 
2019-07-25 13:10:56,967 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:11:01,973 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:11:02,294 - MainProcess[MainThread] - BrowserManager       - INFO    : BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/home/jim/dproject/random-workplace/OpenWPM-master/automation/DeployBrowsers/deploy_firefox.py", line 105, in deploy_firefox
    display.start()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/abstractdisplay.py", line 168, in start
    raise XStartTimeoutError(msg % d)
XStartTimeoutError: Failed to start X on display ":1001" (xdpyinfo check failed).

2019-07-25 13:11:02,297 - MainProcess[MainThread] - BrowserManager       - ERROR   : BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: False  | Browser Launched: False  | Browser Ready: False 
2019-07-25 13:11:02,298 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Attempting to kill BrowserManager with pid 19089. Display PID: None | Display Port: None | Browser PID: None
2019-07-25 13:11:02,298 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Spawn attempt 3 
2019-07-25 13:11:06,978 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
2019-07-25 13:11:11,984 - MainProcess[MainThread] - BaseAggregator       - DEBUG   : Status update; current record queue size: 0
```

**Comment by gitbbb** [comment]
It's weird, after restart the OS and i tried the command once again, and it works!

```
jim$ python demo.py 
fatal: not a git repository (or any of the parent directories): .git
TaskManager          - INFO     - 

OpenWPM Version: 0.10.0
Firefox Version: 68.0

========== Manager Configuration ==========
{
  "aggregator_address": [
    "127.0.0.1",
    51645
  ],
  "data_directory": "/home/jim/Desktop/",
  "database_name": "/home/jim/Desktop/crawl-data.sqlite",
  "failure_limit": null,
  "log_directory": "/home/jim/Desktop/",
  "log_file": "/home/jim/Desktop/openwpm.log",
  "logger_address": [
    "127.0.0.1",
    60843
  ],
  "num_browsers": 3,
  "output_format": "local",
  "screenshot_path": "/home/jim/Desktop/screenshots",
  "source_dump_path": "/home/jim/Desktop/sources",
  "testing": false
}

========== Browser Configuration ==========
Keys:
{
  "crawl_id": 0,
  "adblock-plus": 1,
  "bot_mitigation": 2,
  "browser": 3,
  "cookie_instrument": 4,
  "disable_flash": 5,
  "disconnect": 6,
  "donottrack": 7,
  "extension_enabled": 8,
  "ghostery": 9,
  "headless": 10,
  "http_instrument": 11,
  "https-everywhere": 12,
  "js_instrument": 13,
  "navigation_instrument": 14,
  "prefs": 15,
  "random_attributes": 16,
  "save_all_content": 17,
  "save_javascript": 18,
  "tp_cookies": 19,
  "tracking-protection": 20,
  "ublock-origin": 21
}

  0  1      2      3        4     5      6      7      8     9      10     11    12     13    14    15    16     17     18     19      20     21
---  -----  -----  -------  ----  -----  -----  -----  ----  -----  -----  ----  -----  ----  ----  ----  -----  -----  -----  ------  -----  -----
  1  False  False  firefox  True  False  False  False  True  False  True   True  False  True  True  {}    False  False  False  always  False  False
  2  False  False  firefox  True  False  False  False  True  False  False  True  False  True  True  {}    False  False  False  always  False  False
  3  False  False  firefox  True  False  False  False  True  False  False  True  False  True  True  {}    False  False  False  always  False  False

========== Input profile tar files ==========
  No profile tar files specified

========== Output (archive) profile dirs ==========
  No profile archive directories specified


BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: ('GET', 'http://www.example.com', 3, 1)
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: ('GET', 'http://www.example.com', 3, 3)
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: ('GET', 'http://www.example.com', 3, 2)
BrowserManager       - INFO     - BROWSER 2: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 1: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 3: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: ('GET', 'http://www.princeton.edu', 3, 5)
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: ('GET', 'http://www.princeton.edu', 3, 6)
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: ('GET', 'http://www.princeton.edu', 3, 4)
BrowserManager       - INFO     - BROWSER 2: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 1: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 3: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: ('GET', 'http://citp.princeton.edu/', 3, 7)
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: ('GET', 'http://citp.princeton.edu/', 3, 8)
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: ('GET', 'http://citp.princeton.edu/', 3, 9)
BaseAggregator       - INFO     - Received shutdown signal!

```
