### ISSUE TITLE
Cannot run demo.py

### ISSUE THREAD

**Issue by SaloniH** [mozilla/OpenWPM#425]
Hello, I am using MacOS Mojave Version 10.14.5 with latest Docker and trying to install OpenWPM. After installation while running demo.py, I get the following error continuously even after multiple trials of reinstall.

==============================================================

root@dafa11160f3b:/opt/OpenWPM# python demo.py
No handlers could be found for logger "pyvirtualdisplay.abstractdisplay"
BrowserManager       - INFO     - BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 173, in deploy_firefox
    driver.install_addon(ext_loc, temporary=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: No such file or directory: /opt/OpenWPM/automation/Extension/firefox/openwpm.xpi

BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
No handlers could be found for logger "pyvirtualdisplay.abstractdisplay"
BrowserManager       - INFO     - BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 173, in deploy_firefox
    driver.install_addon(ext_loc, temporary=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: No such file or directory: /opt/OpenWPM/automation/Extension/firefox/openwpm.xpi

BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
No handlers could be found for logger "pyvirtualdisplay.abstractdisplay"
BrowserManager       - INFO     - BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 173, in deploy_firefox
    driver.install_addon(ext_loc, temporary=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: No such file or directory: /opt/OpenWPM/automation/Extension/firefox/openwpm.xpi

BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
No handlers could be found for logger "pyvirtualdisplay.abstractdisplay"
BrowserManager       - INFO     - BROWSER 1: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 360, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 173, in deploy_firefox
    driver.install_addon(ext_loc, temporary=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: No such file or directory: /opt/OpenWPM/automation/Extension/firefox/openwpm.xpi

BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
Traceback (most recent call last):
  File "demo.py", line 37, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params)
  File "/opt/OpenWPM/automation/TaskManager.py", line 123, in __init__
    self._launch_browsers()
  File "/opt/OpenWPM/automation/TaskManager.py", line 161, in _launch_browsers
    self.close()
  File "/opt/OpenWPM/automation/TaskManager.py", line 571, in close
    self._shutdown_manager()
  File "/opt/OpenWPM/automation/TaskManager.py", line 266, in _shutdown_manager
    browser.shutdown_browser(during_init)
  File "/opt/OpenWPM/automation/BrowserManager.py", line 307, in shutdown_browser
    self.kill_browser_manager()
  File "/opt/OpenWPM/automation/BrowserManager.py", line 231, in kill_browser_manager
    self.crawl_id, self.browser_manager.pid, self.display_pid,
AttributeError: 'NoneType' object has no attribute 'pid'

===============================================================

**Comment by SaloniH** [comment]
I have tried native MacOS install as well after a cleanup but that also gives the exact same error.

**Comment by motin** [comment]
To run OpenWPM within a Docker container, turn on headless mode for all browsers, ie remove https://github.com/mozilla/OpenWPM/blob/a337b52eb172ceed9e2ab092a4ba0e1f7421ad29/demo.py#L29 and insert `     browser_params[i]['headless'] = True` instead.

For the [native MacOS install](https://github.com/mozilla/OpenWPM/wiki/Running-OpenWPM-natively-on-macOS), headless mode is not supported, so insert `     browser_params[i]['headless'] = False` instead and then try again :)
