### ISSUE TITLE
Python3 Base Aggregator Shutdown freeze/hang

### ISSUE THREAD

**Issue by Otteas** [mozilla/OpenWPM#487]
Hello,
I'am trying to run a custom script using python 3.6, but most of the time it frezzes after initiating manager.close() With 2.7 i could not obeserve these freezes.
Furthermore i could observer it freezes in 3.6 when this Info appears: 
'TaskManager          - INFO     - BROWSER 359: Received failure status while executing command: GET',
though this Info also appears in 2.7, the freeze only happens in 3.6
It seems to be reproducible with the URL: `https://crptgate.com`, but seldom it works just fine but most of the time a exception is called. 
Using Ubuntu 18.04
Some more deteiled info:

```
BrowserManager       - INFO     - BROWSER 281: EXECUTING COMMAND: ('GET', 'https://crptgate.com', 0, 1815)
BrowserManager       - ERROR    - BROWSER 281: WebDriverException while executing command
Traceback (most recent call last):
  File "/home/lukas/openwpm/OpenWPM-master/automation/BrowserManager.py", line 485, in BrowserManager
    browser_params, manager_params, extension_socket)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/command_executor.py", line 15, in execute_command
    extension_socket=extension_socket)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/browser_commands.py", line 142, in get_website
    bot_mitigation(webdriver)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/browser_commands.py", line 55, in bot_mitigation
    action.perform()
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://marionette/content/event.js :: event.synthesizeMouseAtPoint :: line 175"  data: no]

Exception in thread Thread-115:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 236, in _start_listener
    self._process_record(obj)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 244, in _process_record
    self._handle_serialized_writes(obj)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 269, in _handle_serialized_writes
    obj['exc_info'] = dill.loads(six.ensure_str(obj['exc_info']))
  File "/home/lukas/.local/lib/python3.6/site-packages/six.py", line 888, in ensure_str
    s = s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
TaskManager          - INFO     - BROWSER 281: Received failure status while executing command: GET
BrowserManager       - INFO     - BROWSER 282: EXECUTING COMMAND: ('RUN_CUSTOM_FUNCTION', <function collect_privacy_links at 0x7f9c5a77e1e0>, ('https://zdf.de', 'privacyurllistUSA-Kalifornien.csv', ('127.0.0.1', 33779), 'USA-Kalifornien'))
BaseAggregator       - INFO     - Received shutdown signal!
BrowserManager       - ERROR    - BROWSER 280: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False
^CProcess Process-119:
Process Process-69:
Traceback (most recent call last):
  File "openwpm_custom_function_command.py", line 186, in <module>
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lukas/openwpm/OpenWPM-master/automation/utilities/multiprocess_utils.py", line 42, in run
    mp.Process.run(self)
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukas/openwpm/OpenWPM-master/automation/BrowserManager.py", line 458, in BrowserManager
    time.sleep(0.001)
KeyboardInterrupt
    collect_privacy_proxy_test(alexa_urls, i)             #tr_al_urls, i)
  File "openwpm_custom_function_command.py", line 72, in collect_privacy_proxy_test
    manager.close()
  File "/home/lukas/openwpm/OpenWPM-master/automation/TaskManager.py", line 597, in close
    self._shutdown_manager()
  File "/home/lukas/openwpm/OpenWPM-master/automation/TaskManager.py", line 266, in _shutdown_manager
    self.logging_server.close()
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 282, in close
    self._status_queue.join()
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 308, in join
    self._cond.wait()
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/synchronize.py", line 267, in wait
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lukas/openwpm/OpenWPM-master/automation/utilities/multiprocess_utils.py", line 42, in run
    mp.Process.run(self)
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukas/openwpm/OpenWPM-master/automation/BrowserManager.py", line 457, in BrowserManager
    if command_queue.empty():
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 123, in empty
    return not self._poll()
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 260, in poll
    return self._poll(timeout)
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 418, in _poll
    return bool(r)
KeyboardInterrupt
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt

```

**Last lines of log related to previous exception:**
```
2019-09-03 15:02:00,051 - MainProcess[Thread-214]- BrowserManager       - INFO    : BROWSER 282: EXECUTING COMMAND: ('GET', 'https://zdf.de', 0, 1814)
2019-09-03 15:02:00,149 - MainProcess[MainThread]- BaseAggregator       - DEBUG   : Status update; current record queue size: 1. current number of threads: 5.
2019-09-03 15:02:00,280 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : Visit Id: 1814
2019-09-03 15:02:01,878 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522921878	Marionette	INFO	Listening on port 33275
2019-09-03 15:02:01,952 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522921951	Marionette	WARN	TLS certificate errors will be ignored for this session
2019-09-03 15:02:02,045 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522922045	addons.xpi	WARN	Failed to parse recommendation: TypeError: NetworkError when attempting to fetch resource. No traceback available
2019-09-03 15:02:02,149 - MainProcess[Thread-216]- deploy_firefox       - DEBUG   : BROWSER 281: OpenWPM Firefox extension loaded
2019-09-03 15:02:02,167 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : Navigation instrumentation enabled
2019-09-03 15:02:02,170 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522922170	addons.xpi	WARN	Failed to parse recommendation: TypeError: NetworkError when attempting to fetch resource. No traceback available
2019-09-03 15:02:02,177 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : Cookie instrumentation enabled
2019-09-03 15:02:02,178 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : Javascript instrumentation enabled
2019-09-03 15:02:02,222 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: console.log: WebExtensions: Wrote to /tmp/rust_mozprofile.VOoDK68oxKhQ/extension_port.txt
2019-09-03 15:02:02,251 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : HTTP Instrumentation enabled
2019-09-03 15:02:02,262 - MainProcess[Thread-216]- BrowserManager       - DEBUG   : BROWSER 281: Looking for extension port information in /tmp/rust_mozprofile.VOoDK68oxKhQ/
2019-09-03 15:02:02,264 - MainProcess[Thread-216]- BrowserManager       - DEBUG   : BROWSER 281: Connecting to extension on port 34021
2019-09-03 15:02:02,265 - MainProcess[Thread-216]- BrowserManager       - DEBUG   : BROWSER 281: BrowserManager ready.
2019-09-03 15:02:02,266 - MainProcess[Thread-216]- BrowserManager       - DEBUG   : BROWSER 281: Browser spawn sucessful!
2019-09-03 15:02:02,354 - MainProcess[MainThread]- TaskManager          - DEBUG   : Checking command failure status indicator...
2019-09-03 15:02:02,358 - MainProcess[MainThread]- BrowserManager       - DEBUG   : BROWSER 280: Closing browser manager...
2019-09-03 15:02:02,359 - MainProcess[MainThread]- BrowserManager       - DEBUG   : BROWSER 280: Closing browser...
2019-09-03 15:02:02,360 - MainProcess[MainThread]- BrowserManager       - DEBUG   : BROWSER 280: Joining command thread
2019-09-03 15:02:02,363 - MainProcess[Thread-216]- BrowserManager       - INFO    : BROWSER 281: EXECUTING COMMAND: ('GET', 'https://crptgate.com', 0, 1815)
2019-09-03 15:02:02,506 - MainProcess[Thread-115]- FirefoxExtension     - DEBUG   : Visit Id: 1815
2019-09-03 15:02:04,205 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522924204	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
2019-09-03 15:02:04,206 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: bail@chrome://marionette/content/sync.js:223:64
2019-09-03 15:02:04,479 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522924479	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
2019-09-03 15:02:04,480 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: bail@chrome://marionette/content/sync.js:223:64
2019-09-03 15:02:04,754 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522924754	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
2019-09-03 15:02:04,755 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: bail@chrome://marionette/content/sync.js:223:64
2019-09-03 15:02:05,019 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: 1567522925019	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
2019-09-03 15:02:05,020 - MainProcess[log-interceptor-281]- selenium_firefox     - DEBUG   : BROWSER 281: driver: bail@chrome://marionette/content/sync.js:223:64
2019-09-03 15:02:05,175 - MainProcess[MainThread]- BaseAggregator       - DEBUG   : Status update; current record queue size: 39. current number of threads: 6.


```

**----------------------------------------
some more exceptions:**

```
BrowserManager       - INFO     - BROWSER 407: EXECUTING COMMAND: ('GET', 'https://crptgate.com', 0, 5528)
BrowserManager       - INFO     - BROWSER 408: EXECUTING COMMAND: ('GET', 'https://google.com', 0, 5529)
BrowserManager       - ERROR    - BROWSER 407: WebDriverException while executing command
Traceback (most recent call last):
  File "/home/lukas/openwpm/OpenWPM-master/automation/BrowserManager.py", line 485, in BrowserManager
    browser_params, manager_params, extension_socket)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/command_executor.py", line 15, in execute_command
    extension_socket=extension_socket)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/browser_commands.py", line 142, in get_website
    bot_mitigation(webdriver)
  File "/home/lukas/openwpm/OpenWPM-master/automation/Commands/browser_commands.py", line 55, in bot_mitigation
    action.perform()
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lukas/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://marionette/content/event.js :: event.synthesizeMouseAtPoint :: line 175"  data: no]

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 236, in _start_listener
    self._process_record(obj)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 244, in _process_record
    self._handle_serialized_writes(obj)
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 269, in _handle_serialized_writes
    obj['exc_info'] = dill.loads(six.ensure_str(obj['exc_info']))
  File "/home/lukas/.local/lib/python3.6/site-packages/six.py", line 888, in ensure_str
    s = s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

TaskManager          - INFO     - BROWSER 407: Received failure status while executing command: GET
BrowserManager       - INFO     - BROWSER 407: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 407: Launching browser...
...
...
BrowserManager       - INFO     - BROWSER 408: EXECUTING COMMAND: ('RUN_CUSTOM_FUNCTION', <function collect_privacy_links at 0x7f30cc4891e0>, ('https://spiegel.de', 'privacyurllistUSA-Kalifornien.csv', ('127.0.0.1', 42389), 'USA-Kalifornien'))
BaseAggregator       - INFO     - Received shutdown signal!
^CTraceback (most recent call last):
  File "openwpm_custom_function_command.py", line 185, in <module>
    collect_privacy_proxy_test(tr_al_urls, i)             #tr_al_urls, i)
  File "openwpm_custom_function_command.py", line 71, in collect_privacy_proxy_test
    manager.close()
  File "/home/lukas/openwpm/OpenWPM-master/automation/TaskManager.py", line 597, in close
    self._shutdown_manager()
  File "/home/lukas/openwpm/OpenWPM-master/automation/TaskManager.py", line 266, in _shutdown_manager
    self.logging_server.close()
  File "/home/lukas/openwpm/OpenWPM-master/automation/MPLogger.py", line 282, in close
    self._status_queue.join()
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 308, in join
    self._cond.wait()
  File "/home/lukas/.local/lib/python3.6/site-packages/multiprocess/synchronize.py", line 267, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt





```

**Comment by englehardt** [comment]
Closing because of the age of this. Feel free to file a new issue if you're still having issues. Sorry we never followed up!
