### ISSUE TITLE
Parquet-related error in S3Aggregator

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#498]
See the [most recent run](https://travis-ci.org/mozilla/OpenWPM/jobs/594846373#L3016-L3046) of the test suite:

```
multiprocess_utils   - ERROR    - Exception in child process.

Traceback (most recent call last):

  File "/home/travis/build/mozilla/OpenWPM/automation/utilities/multiprocess_utils.py", line 42, in run

    mp.Process.run(self)

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/multiprocess/process.py", line 114, in run

    self._target(*self._args, **self._kwargs)

  File "/home/travis/build/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 56, in listener_process_runner

    listener.drain_queue()

  File "/home/travis/build/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 320, in drain_queue

    self._send_to_s3(force=True)

  File "/home/travis/build/mozilla/OpenWPM/automation/DataAggregator/S3Aggregator.py", line 227, in _send_to_s3

    flavor='spark'

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pyarrow/parquet.py", line 1450, in write_to_dataset

    write_table(subtable, f, **kwargs)

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pyarrow/parquet.py", line 1343, in write_table

    **kwargs) as writer:

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pyarrow/parquet.py", line 448, in __init__

    **options)

  File "pyarrow/_parquet.pyx", line 1220, in pyarrow._parquet.ParquetWriter.__cinit__

    def __cinit__(self, where, Schema schema, use_dictionary=None,

TypeError: __cinit__() got an unexpected keyword argument 'preserve_index'

Process Process-17:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/multiprocess/process.py", line 267, in _bootstrap

    self.run()

  File "/home/travis/build/mozilla/OpenWPM/automation/utilities/multiprocess_utils.py", line 50, in run

    raise e

TypeError: __cinit__() got an unexpected keyword argument 'preserve_index'
```

It looks like the Parquet interface has been updated.

**Comment by englehardt** [comment]
This argument was removed by https://github.com/apache/arrow/pull/5130.
