### ISSUE TITLE
Are we ok with not fully error handling "Crash in driver"

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#688]
I was just reviewing some tests and noticed the following.

The browser is crashing in the test, perhaps intentionally, which is fine, but we are getting to `    display_pid, display_port = display.pid, display.cmd_param[-1][1:]` line of code which won't work because the browser's not running.

Should we better error handle this? Not sure we should, just bringing it up for discussion.

```
127.0.0.1 - - [18/Jun/2020 17:50:52] "GET /test_pages/recursive_iframes/child3c.html HTTP/1.1" 200 -

127.0.0.1 - - [18/Jun/2020 17:50:52] "GET /test_pages/recursive_iframes/child3d.html HTTP/1.1" 200 -

127.0.0.1 - - [18/Jun/2020 17:50:52] "GET /test_pages/recursive_iframes/child4a.html HTTP/1.1" 200 -

127.0.0.1 - - [18/Jun/2020 17:50:52] "GET /test_pages/recursive_iframes/child5a.html HTTP/1.1" 200 -

127.0.0.1 - - [18/Jun/2020 17:50:52] "GET /test_pages/recursive_iframes/child6a.html HTTP/1.1" 200 -

BrowserManager       - INFO     - BROWSER 1: Launching browser...

BrowserManager       - ERROR    - BROWSER 1: Crash in driver, restarting browser manager

Traceback (most recent call last):

  File "/home/travis/build/mozilla/OpenWPM/automation/BrowserManager.py", line 450, in BrowserManager

    driver, prof_folder, browser_settings = deploy_browser.deploy_browser(

  File "/home/travis/build/mozilla/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 13, in deploy_browser

    return deploy_firefox.deploy_firefox(status_queue, browser_params,

  File "/home/travis/build/mozilla/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 126, in deploy_firefox

    display_pid, display_port = display.pid, display.cmd_param[-1][1:]

AttributeError: 'Display' object has no attribute 'cmd_param'

BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: False  | Browser Launched: False  | Browser Ready: False 
```

**Comment by birdsarah** [comment]
Closing this. I think this is actually related to pyvirtualdisplay update.
