### ISSUE TITLE
v0.13.0 on google cloud vm

### ISSUE THREAD

**Issue by MaazBinMusa** [mozilla/OpenWPM#909]
``Hi, 

I am trying to run v0.13.0 on a google cloud VM

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

I used this to clone the tag

`git clone --depth 1 --branch v0.13.0 https://github.com/mozilla/OpenWPM.git
`

I ran the install script and conda is installed but it keeps giving me this error

```

2021-04-29 18:04:23,553 - MainProcess[MainThread]- browser_manager      - INFO    : BROWSER 2420832559: Launching browser...
2021-04-29 18:04:23,556 - MainProcess[MainThread]- browser_manager      - DEBUG   : BROWSER 2420832559: Spawn attempt 0
2021-04-29 18:04:23,558 - MainProcess[MainThread]- storage_controller   - DEBUG   : Initializing new handler
2021-04-29 18:04:23,571 - MainProcess[MainThread]- deploy_firefox       - DEBUG   : BROWSER 2420832559: Saved extension config file to: /tmp/firefox_profile_8ianm5uk/browser_params.json
2021-04-29 18:04:23,581 - MainProcess[log-interceptor-2420832559]- selenium_firefox     - DEBUG   : BROWSER 2420832559: driver: 1619719463581   geckodriver     INFO    Listening on 127.0.0.1:36839
2021-04-29 18:04:24,589 - MainProcess[log-interceptor-2420832559]- selenium_firefox     - DEBUG   : BROWSER 2420832559: driver: 1619719464589   mozrunner::runner       INFO    Running command: "/home/maazbinmusa94/OpenWPM/firefox-bin/firefox-bin" "--marionette" "-profile" "/tmp/firefox_profile_8ianm5uk" "-headless" "--width=1$
2021-04-29 18:04:24,594 - MainProcess[log-interceptor-2420832559]- selenium_firefox     - DEBUG   : BROWSER 2420832559: driver: XPCOMGlueLoad error for file /home/maazbinmusa94/OpenWPM/firefox-bin/libmozgtk.so:
2021-04-29 18:04:24,595 - MainProcess[log-interceptor-2420832559]- selenium_firefox     - DEBUG   : BROWSER 2420832559: driver: libgtk-3.so.0: cannot open shared object file: No such file or directory
2021-04-29 18:04:24,595 - MainProcess[log-interceptor-2420832559]- selenium_firefox     - DEBUG   : BROWSER 2420832559: driver: Couldn't load XPCOM.
2021-04-29 18:04:24,694 - MainProcess[MainThread]- browser_manager      - ERROR   : BROWSER 2420832559: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/home/maazbinmusa94/OpenWPM/openwpm/browser_manager.py", line 682, in run
    driver, browser_profile_path, display = deploy_firefox.deploy_firefox(
  File "/home/maazbinmusa94/OpenWPM/openwpm/deploy_browsers/deploy_firefox.py", line 163, in deploy_firefox
    driver = webdriver.Firefox(
  File "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255

2021-04-29 18:04:24,702 - MainProcess[MainThread]- browser_manager      - ERROR   : BROWSER 2420832559: Spawn unsuccessful  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False
2021-04-29 18:04:24,702 - MainProcess[MainThread]- browser_manager      - DEBUG   : BROWSER 2420832559: Closing browser...

```

Am I missing some packages on the new VM? I installed `packagekit-gtk3-module` as well and still no luck

**Comment by MaazBinMusa** [comment]
I started another new VM with the latest openwpm and same issue. There is an error when running the install script


```
> dtrace-provider@0.8.8 install /home/maazbinmusa94/OpenWPM/openwpm/Extension/firefox/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 4.19.0-16-cloud-amd64
gyp ERR! command "/home/maazbinmusa94/miniconda3/envs/openwpm/bin/node" "/home/maazbinmusa94/miniconda3/envs/openwpm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/maazbinmusa94/OpenWPM/openwpm/Extension/firefox/node_modules/dtrace-provider
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by vringar** [comment]
What happens if you run `<openwpm_root_dir>/firefox-bin/firefox-bin --version`?

**Comment by MaazBinMusa** [comment]
> What happens if you run `<openwpm_root_dir>/firefox-bin/firefox-bin --version`?

XPCOMGlueLoad error for file /home/maazbinmusa94/OpenWPM/firefox-bin/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

**Comment by vringar** [comment]
Consider installing libx11-xcb so that it can be found by Firefox.

**Comment by MaazBinMusa** [comment]
I will try this out. I was able to make v13 work by running it in its docker. It sometimes starts giving the following error but I think Openwpm recovers catches and manages the crash and continues the crawl


```
Exception in thread Thread-27860:                                                                                                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                      
  File "/opt/OpenWPM/openwpm/BrowserManager.py", line 294, in close_browser_manager                                                                                                                                                                                                                                                     
    status = self.status_queue.get(True, 30)                                                                                                                                                                                                                                                                                            
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/multiprocess/queues.py", line 111, in get                                                                                                                                                                                                                               
    raise Empty                                                                                                                                                                                                                                                                                                                         
_queue.Empty                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                        
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                      
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_common.py", line 446, in wrapper                                                                                                                                                                                                                                
    ret = self._cache[fun]                                                                                                                                                                                                                                                                                                              
AttributeError: _cache                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                        
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                      
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_pslinux.py", line 1517, in wrapper                                                                                                                                                                                                                              
    return fun(self, *args, **kwargs)                                                                                                                                                                                                                                                                                                   
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_common.py", line 449, in wrapper                                                                                                                                                                                                                                
    return fun(self)                                                                                                                                                                                                                                                                                                                    
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_pslinux.py", line 1559, in _parse_stat_file                                                                                                                                                                                                                     
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:                                                                                                                                                                                                                                                                
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_common.py", line 710, in open_binary                                                                                                                                                                                                                            
    return open(fname, "rb", **kwargs)                                                                                                                                                                                                                                                                                                  
FileNotFoundError: [Errno 2] No such file or directory: '/proc/7229/stat'                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                        
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                      
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 352, in _init                                                                                                                                                                                                                                 
    self.create_time()                                                                                                                                                                                                                                                                                                                  
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 708, in create_time                                                                                                                                                                                                                           
    self._create_time = self._proc.create_time()                                                                                                                                                                                                                                                                                        
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_pslinux.py", line 1517, in wrapper                                                                                                                                                                                                                              
    return fun(self, *args, **kwargs)                                                                                                                                                                                                                                                                                                   
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_pslinux.py", line 1729, in create_time                                                                                                                                                                                                                          
    ctime = float(self._parse_stat_file()['create_time'])                                                                                                                                                                                                                                                                               
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/_pslinux.py", line 1524, in wrapper                                                                                                                                                                                                                              
    raise NoSuchProcess(self.pid, self._name)                                                                                                                                                                                                                                                                                           
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=7229)                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                        
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                      
  File "/opt/miniconda/envs/openwpm/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                                                                                                                                                                          
    self.run()                                                                                                                                                                                                                                                                                                                          
  File "/opt/miniconda/envs/openwpm/lib/python3.8/threading.py", line 870, in run                                                                                                                                                                                                                                                       
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                                                                                                           
  File "/opt/OpenWPM/openwpm/TaskManager.py", line 602, in _issue_command                                                                                                                                                                                                                                                               
    success = browser.restart_browser_manager(clear_profile=reset)                                                                                                                                                                                                                                                                      
  File "/opt/OpenWPM/openwpm/BrowserManager.py", line 233, in restart_browser_manager                                                                                                                                                                                                                                                   
    self.close_browser_manager()                                                                                                                                                                                                                                                                                                        
  File "/opt/OpenWPM/openwpm/BrowserManager.py", line 300, in close_browser_manager                                                                                                                                                                                                                                                     
    self.kill_browser_manager()                                                                                                                                                                                                                                                                                                         
  File "/opt/OpenWPM/openwpm/BrowserManager.py", line 380, in kill_browser_manager                                                                                                                                                                                                                                                      
    psutil.Process(pid=self.geckodriver_pid), self.logger                                                                                                                                                                                                                                                                               
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 324, in __init__                                                                                                                                                                                                                              
    self._init(pid)                                                                                                                                                                                                                                                                                                                     
  File "/opt/miniconda/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 365, in _init                                                                                                                                                                                                                                 
    raise NoSuchProcess(pid, None, msg)                                                                                                                                                                                                                                                                                                 
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 7229  
```

I am going to close this for now since I found a work around, but I will try installing the libx11 and get back here.
